# Generated by Django 4.0.3 on 2022-04-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="session",
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
