# Generated by Django 4.0.3 on 2022-04-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_question_session_delete_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multichoiceanswer",
            old_name="multi_choice_question",
            new_name="question",
        ),
    ]
